const test = {
    anal: [ 'gif', 'mp4', 'jpg', 'jpeg' ],
    ass: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    bdsm: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    boobs: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    cock: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    cumshots: [ 'gif', 'mp4', 'jpg' ],
    'double-penetration': [ 'gif', 'jpg' ],
    feet: [ 'gif', 'png', 'jpg', 'jpeg' ],
    femdom: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    furry: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    hentai: [ 'gif' ],
    oral: [ 'gif', 'mp4', 'png', 'jpg' ],
    petite: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    pornstar: [ 'gif', 'mp4', 'jpg' ],
    pov: [ 'gif', 'mp4', 'png', 'jpg' ],
    public: [ 'gif', 'mp4', 'png', 'jpg' ],
    pussy: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    solo: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    toys: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    uniform: [ 'gif', 'mp4', 'jpg' ],
  }